kind: Service
apiVersion: v1
metadata:
  name: das2go
spec:
  selector:
    app: das2go
  ports:
    - port: 8212
      targetPort: 8212
      nodePort: 30212
  type: NodePort
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: das2go
  name: das2go
spec:
  selector:
    matchLabels:
      app: das2go
  replicas: 1
  template:
    metadata:
      labels:
        app: das2go
    spec:
      hostNetwork: true
      containers:
      - image: cmssw/das2go
        name: das2go
        tty: true
        stdin: true
        lifecycle:
          postStart:
            exec:
              command:
              - bash
              - -c
              - sudo chmod 0400 /etc/secrets/server.key /etc/secrets/robotkey.pem
        ports:
        - containerPort: 8212
          protocol: TCP
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          defaultMode: 0400
        - name: etc-grid-security
          mountPath: /etc/grid-security
      volumes:
      - name: secrets
        secret:
          secretName: das-secrets
      - name: etc-grid-security
        hostPath:
            path: /etc/grid-security
