kind: Service
apiVersion: v1
metadata:
  name: dbs2go
spec:
  selector:
    app: dbs2go
  ports:
    - port: 8989
      targetPort: 8989
      nodePort: 30989
  type: NodePort
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: dbs2go
  name: dbs2go
spec:
  selector:
    matchLabels:
      app: dbs2go
  replicas: 1
  template:
    metadata:
      labels:
        app: dbs2go
    spec:
      hostNetwork: true
      containers:
      - image: veknet/dbs2go
        name: dbs2go
        tty: true
        stdin: true
        ports:
        - containerPort: 8989
          protocol: TCP
        volumeMounts:
        - name: secrets
          mountPath: "/etc/secrets"
          readOnly: true
        - name: etc-grid-security
          mountPath: /etc/grid-security
      volumes:
      - name: secrets
        secret:
          secretName: dbs-secrets
      - name: etc-grid-security
        hostPath:
            path: /etc/grid-security
